server:
  port: 9091

mybatis:
  mapper-locations:
  - classpath:/mapper/*.xml
  type-aliases-package: kr.ac.kopo.kidscare.model
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: KidsCare_UI
  datasource: 
    driver-class-name: oracle.jdbc.OracleDriver
    password: kidscare
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: kidscare 
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      location: D:/upload

    
  mvc:
    static-path-pattern: "/static/**"

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    
logging:
  level:
    '[org.springframework]': trace

  
