
logging:
  level:
    org:
      springframework:
        security: TRACE
        

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: kr.ac.kopo.kidscare.model
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 9090
spring:
  application:
    name: KidsCare
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: kidscare
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: kidscare 
      
