
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9090
spring:
  application:
    name: KidsCare
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: kidscare
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: kidscare
